package pipeline

import (
	"fmt"
	"os"
	"path/filepath"
	"runtime/debug"
	"strings"
	"time"

	"github.com/trilithus/stimconv/internal/config"
)

// ReadmeName is the settings report's file name: README.md inside a default
// output folder (one input per folder), <input name>.md in a chosen folder,
// where several inputs may share it.
func ReadmeName(input string, customOutDir bool) string {
	if !customOutDir {
		return "README.md"
	}
	return strings.TrimSuffix(filepath.Base(input), filepath.Ext(input)) + ".md"
}

// readmeInfo is what writeReadme reports besides the settings.
type readmeInfo struct {
	Input    string
	Source   string // format / container / track description
	Preset   string
	Files    []string
	Warnings []string
	Hints    string
}

// writeReadme writes the settings report next to the funscripts.
func writeReadme(path string, cfg config.Config, info readmeInfo) error {
	var b strings.Builder
	name := filepath.Base(info.Input)
	fmt.Fprintf(&b, "# %s\n\n", name)
	fmt.Fprintf(&b, "Funscripts generated by stimconv %s on %s.\n\n", version(), time.Now().Format("2006-01-02 15:04"))
	fmt.Fprintf(&b, "| | |\n|---|---|\n")
	fmt.Fprintf(&b, "| Original file | `%s` |\n", mdCell(name))
	abs, err := filepath.Abs(info.Input)
	if err != nil {
		abs = info.Input
	}
	fmt.Fprintf(&b, "| Original path | `%s` |\n", mdCell(abs))
	fmt.Fprintf(&b, "| Source | %s |\n", mdCell(info.Source))
	fmt.Fprintf(&b, "| Preset | %s |\n", mdCell(info.Preset))
	fmt.Fprintf(&b, "\n## Settings\n\n\"(not used)\" marks settings that have no effect with the other choices, for example tri-phase options in a quad-phase conversion.\n\n")
	fmt.Fprintf(&b, "| Setting | Key | Value | Default |\n|---|---|---|---|\n")
	def := config.Default()
	for i := range config.Options {
		o := &config.Options[i]
		v, d := fmtValue(o.Get(&cfg)), fmtValue(o.Get(&def))
		isDef := "yes"
		if v != d {
			isDef = "no (default " + d + ")"
		}
		label := o.Label
		if o.Group == config.GroupRanges {
			label = "Range " + o.Label
		}
		shown := v
		if o.OnlyIf != nil && !o.OnlyIf(cfg) {
			shown += " (not used)"
		}
		fmt.Fprintf(&b, "| %s | `%s` | %s | %s |\n", mdCell(label), o.Key, mdCell(shown), mdCell(isDef))
	}
	if len(info.Files) > 0 {
		fmt.Fprintf(&b, "\n## Files\n\n")
		for _, f := range info.Files {
			fmt.Fprintf(&b, "- `%s`\n", filepath.Base(f))
		}
	}
	if len(info.Warnings) > 0 {
		fmt.Fprintf(&b, "\n## Warnings\n\n")
		for _, w := range info.Warnings {
			fmt.Fprintf(&b, "- %s\n", w)
		}
	}
	fmt.Fprintf(&b, "\n## restim\n\n%s\n", info.Hints)
	fmt.Fprintf(&b, "\nReproduce with the CLI: save these settings as a JSON config (GUI: Export config…) and run `stimconv cli --config <file> \"%s\"`.\n", name)
	return os.WriteFile(path, []byte(b.String()), 0o644)
}

func fmtValue(v any) string {
	switch x := v.(type) {
	case float64:
		return fmt.Sprintf("%g", x)
	default:
		return fmt.Sprint(x)
	}
}

// mdCell escapes text for a Markdown table cell.
func mdCell(s string) string {
	return strings.NewReplacer("|", `\|`, "\n", " ").Replace(s)
}

// version is the module version or VCS revision stimconv was built from.
func version() string {
	bi, ok := debug.ReadBuildInfo()
	if !ok {
		return "(unknown version)"
	}
	if v := bi.Main.Version; v != "" && v != "(devel)" {
		return v
	}
	rev, dirty := "", ""
	for _, s := range bi.Settings {
		switch s.Key {
		case "vcs.revision":
			rev = s.Value
		case "vcs.modified":
			if s.Value == "true" {
				dirty = "-dirty"
			}
		}
	}
	if len(rev) > 12 {
		rev = rev[:12]
	}
	if rev == "" {
		return "(development build)"
	}
	return "rev " + rev + dirty
}
